name: PyPI Release

# https://help.github.com/en/actions/reference/events-that-trigger-workflows
on: # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [main, "release/*"]
  pull_request:
    branches: [main, "release/*"]
    paths:
      - ".github/workflows/publish-pkg.yml"
  release:
    types: [published]

jobs:
  # based on https://github.com/pypa/gh-action-pypi-publish
  build-package:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install `build` dependency
        run: python -m pip install -U build

      - name: Build package
        run: python -m build && ls -lh dist/

      - uses: actions/upload-artifact@v4
        with:
          name: pypi-packages-${{ github.sha }}
          path: dist

  release-upload:
    needs: build-package
    if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: pypi-packages-${{ github.sha }}
          path: dist
      - run: ls -lh dist/

      - name: Upload to release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "dist/*"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  publish-pypi-main:
    needs: build-package
    if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: pypi-packages-${{ github.sha }}
          path: dist
      - run: ls -lh dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.12
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          verbose: true